[install]
# Configure how packages are installed
save = true
save-exact = false
peer = true
production = false
optional = true
dev = true

[install.cache]
dir = ".bun/install/cache"
disable = false

[runtime]
env = ".env"